import React,{useEffect,useState} from 'react';
import { Bell, Briefcase, FileText, LayoutDashboard, LogOut, Menu, MessageSquare, Settings, Users, X } from 'lucide-react';
import { BrandLogo } from '../BrandLogo';
import type { AdminUser } from '../../types';

const nav=[['Dashboard','/admin',LayoutDashboard],['Jobs','/admin/jobs',Briefcase],['Applicants','/admin/applicants',Users],['Staff Requests','/admin/staff-requests',FileText],['Messages','/admin/messages',MessageSquare],['Settings','/admin/settings',Settings]] as const;
export function AdminLayout({path,user,onNavigate,onSignOut,children}:{path:string;user:AdminUser;onNavigate:(path:string)=>void;onSignOut:()=>void;children:React.ReactNode}){
 const [open,setOpen]=useState(false); useEffect(()=>setOpen(false),[path]);
 const sidebar=<aside className="flex h-full w-72 flex-col bg-[#102A43] text-white"><div className="flex h-20 items-center justify-between border-b border-white/10 px-5"><div className="rounded-lg bg-white px-3 py-2"><BrandLogo variant="horizontal" size="sm" showTagline={false}/></div><button className="lg:hidden" onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button></div><nav className="flex-1 space-y-1 px-3 py-5">{nav.map(([label,href,Icon])=>{const active=href==='/admin'?path==='/admin':path.startsWith(href);return <button key={href} onClick={()=>onNavigate(href)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-semibold ${active?'bg-[#2463A7] text-white':'text-slate-300 hover:bg-white/10 hover:text-white'}`}><Icon className="h-4 w-4"/>{label}</button>})}</nav><div className="border-t border-white/10 p-4"><div className="mb-3 flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#F4B942] text-xs font-black text-[#102A43]">{user.initials}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{user.name}</p><p className="truncate text-xs text-slate-400">{user.email}</p></div></div><button onClick={onSignOut} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-slate-300 hover:bg-white/10"><LogOut className="h-4 w-4"/>Sign Out</button></div></aside>;
 return <div className="min-h-screen bg-[#F8F7F3]"><div className="fixed inset-y-0 left-0 z-40 hidden lg:block">{sidebar}</div>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/45" onClick={()=>setOpen(false)} aria-label="Close navigation overlay"/><div className="relative h-full">{sidebar}</div></div>}<div className="lg:pl-72"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#D9E2EC] bg-white/95 px-4 backdrop-blur sm:px-6"><button className="rounded-lg p-2 text-[#102A43] lg:hidden" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button><p className="hidden text-sm font-semibold text-[#627D98] sm:block">Bright Start Administration <span className="ml-2 rounded bg-amber-100 px-2 py-1 text-[10px] font-bold text-amber-800">DEMO</span></p><div className="flex items-center gap-3"><button className="rounded-lg border border-[#D9E2EC] p-2 text-[#627D98]" aria-label="Notifications"><Bell className="h-4 w-4"/></button><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#102A43] text-xs font-black text-white">{user.initials}</span></div></header><main className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">{children}</main></div></div>;
}
